version: 1.0.{build}

install:
  - choco install -y docker -pre
  - choco install -y curl
  - curl.exe -s http://whatismijnip.nl
  - docker --version

build_script:
  - ps: .\build.ps

deploy_script:
  - ps: .\deploy.ps1

test: off

