version: 1.0.{build}

install:
  - choco install -y docker -pre
  - choco install -y docker-compose
  - choco install -y curl
  - curl.exe -s http://whatismijnip.nl
  - echo ""
  - docker --version
  - docker-compose --version

build_script:
  - ps: .\build.ps1

deploy_script:
  - ps: .\deploy.ps1

test: off

