version: 1.0.{build}

install:
  - choco install -y docker -pre
  - choco install -y docker-compose
  - choco install -y curl
  - ps: (curl.exe -s http://whatismijnip.nl) | Write-Output
  - echo ""
  - docker-compose --version
  - docker --version
  - docker version
  - docker info
    
build_script:
  - ps: .\build.ps1

deploy_script:
  - ps: .\deploy.ps1

test: off

